services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./src/public:/var/www/public
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    environment:
      BASE_URL: "http://localhost:8080"
      DELETE_CREDENTIALS: supersecret
      IRC_ANNOUNCE_ENABLE: false
      IRC_ANNOUNCE_HOST: "localhost"
      IRC_ANNOUNCE_PORT: 26656
    volumes:
      - ./src:/var/www
      - ./pastes:/pastes
      - ./archive:/archive
